# theme used
remote_theme: pmarsceill/just-the-docs

title: RAPIDS Demos
description: Containers, demos, and notebooks to explore RAPIDS
baseurl: "/demos/" # the subpath of your site, e.g. /blog

permalink: pretty
exclude: ["README.md"]

aux_links:
    "View RAPIDS on GitHub":
      - "https://github.com/rapidsai"

# Enable or disable the site search
search_enabled: true
